[tool.poetry]
name = "django-libms"
version = "0.1.0"
description = "Library management system"
authors = ["Alexey Vorobyov <alexey.vorobyov.s@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.11"
Django = "~5.0"
bpython = "~0.24"
pytest = "~8.2.2"
pytest-django = "~4.8.0"
mixer = "^7.2.2"
pytest-deadfixtures = "^2.2.1"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings"
python_files = "test*.py"
pythonpath = ". src"
addopts = [
# https://pytest-django.readthedocs.io/en/latest/database.html#reuse-db-reuse-the-testing-database-between-test-runs
    # "--reuse-db",
    "-s",
    "-p no:warnings"
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
