name: CI/CD

on:
    push:
      branches:
        - main
    pull_request:

env:
  IMAGE: ghcr.io/${{ github.repository }}/django-libraryms
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_CONTEXT: ${{ toJson(github) }}
  DATABASE_URL: postgres://postgres:secret@localhost:5432/postgres

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/actions/build

      - name: lint
        run: make lint -e RUN_MAKEMIGRATIONS=0

  test:
    needs: lint
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: build
        uses: ./.github/actions/build

      - name: test
        run: make test
